-- return {
--   'epwalsh/obsidian.nvim',
--   version = '*',
--   event = {
--     'BufReadPre ' .. vim.fn.expand('~') .. '/notes/**.md',
--     'BufNewFile ' .. vim.fn.expand('~') .. '/notes/**.md',
--   },
--   dependencies = {
--     'hrsh7th/nvim-cmp',
--     'nvim-lua/plenary.nvim',
--   },
--   opts = {
--     workspaces = {
--       {
--         name = 'notes',
--         path = '~/notes',
--       },
--     },
--   },
-- }
