vim.g.loaded_netrw = 1 -- NOTE: this might help with neo-tree
vim.g.loaded_netrwPlugin = 1 -- NOTE: this might help with neo-tree
vim.o.cmdheight = 2 -- NOTE: allows hardtime to display alongside modes
vim.o.termguicolors = true -- NOTE: relied on by neo-tree

-- {
--   'NvChad/nvim-colorizer.lua',
--   config = function()
--     require('colorizer').setup(nil,{
--       RGB       = true,
--       RRGGBB    = true,
--       RRGGBBAA  = true,
--       hsl_fn    = true,
--       mode      = 'background',
--       names     = false,
--       rgb_fn    = true,
--     })
--   end,
-- },
-- {
--   'nvim-neo-tree/neo-tree.nvim',
--   branch = 'v3.x',
--   dependencies = {
--     'nvim-tree/nvim-web-devicons',
--     'nvim-lua/plenary.nvim',
--     'MunifTanjim/nui.nvim',
--   },
--   config = true,
-- },
-- {
--   'folke/trouble.nvim',
--   dependencies = {
--     'nvim-tree/nvim-web-devicons'
--   },
--   opts = {},
-- },
--{
--  'ellisonleao/glow.nvim',
--  config = true,
--  cmd = 'Glow'
--},
-- {
--   'folke/twilight.nvim', -- BUG: does nothing
--   config = true,
-- },
-- {
--   'lcheylus/overlength.nvim',
--   config = true,
-- },
-- {
--   'xiyaowong/transparent.nvim',
--   config = function()
--     require('transparent').setup {
--       extra_groups = {
--         'NeoTreeNormal',
--         'NeoTreeNormalNC',
--         'NormalFloat',
--       },
--    }
--   end,
-- },
-- {
--   "m4xshen/hardtime.nvim",
--   dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
--   opts = {
--     enabled = false,
--   }
-- },
-- {
-- 'nvim-pack/nvim-spectre',
--   dependencies = {
--     'nvim-lua/plenary.nvim'
--   },
-- config = function()
--   require('spectre').setup({
--     live_update = true,
--     replace_vim_cmd = 'cdfo',
--     })
--   end,
-- },
-- {
-- 'akinsho/toggleterm.nvim',
-- config = function()
--   require('toggleterm').setup({
--     shade_terminals = false,
--     })
--   end,
-- },
